### ISSUE TITLE
如何进行手眼标定，获得相机坐标系和基坐标系（或世界坐标系）之间转换关系？

### ISSUE THREAD

**Issue by Twilight89** [NikofoxS/hand_eye_rokae#1]
您好~我也购置了一款XB4，但不清楚如何进行手眼标定（因为XB4并不支持ROS）。我使用的是深度相机Realsense435，想将其采集得到的点云数据转换到世界坐标系（机械臂base坐标系下），请问怎么获得相机和基座标系或世界坐标系之间的transformation呢？
Hope for your reply, thanks a lot

**Comment by foxchys** [comment]
> 您好~我也购置了一款XB4，但不清楚如何进行手眼标定（因为XB4并不支持ROS）。我使用的是深度相机Realsense435，想将其采集得到的点云数据转换到世界坐标系（机械臂base坐标系下），请问怎么获得相机和基座标系或世界坐标系之间的transformation呢？
> Hope for your reply, thanks a lot

1、关于标定算法。可以构建AX=XB方程，基于采集到的数据求解该方程中的X即可得到手眼关系(相机和基座标系或世界坐标系之间的transformation)。"eye-in-hand"与"eye-to-hand"在构造方程时，方程中X以及A与B所描述的关系不同。具体可参考Tsai-Lenz算法(论文A new technique for fully autonomous and efficient 3D robotics hand/eye calibration)。OpenCV4.x中有Tsai算法的相关实现[cv::calibrateHandEye](https://docs.opencv.org/4.5.0/d9/d0c/group__calib3d.html#gaebfc1c9f7434196a374c382abf43439b)以及(cv::calibrateRobotWorldHandEye)。相机与标定板之间的关系则可以基于PNP之类的思路求解，具体可参考OpenCV中的相关实现(cv::solvePnP)。
2、关于手眼标定所需数据。机械臂手眼系统常见的相机安装方式分为"eye-in-hand"与"eye-to-hand"两种。手眼标定时，"eye-in-hand"将标定板固定在机械臂基座附近（标定板与机械臂基座之间位姿关系不变），而"eye-to-hand"将标定板固定在机械臂法兰盘上（标定板与法兰盘之间位姿关系不变）。之后，使用相机对标定板进行拍照，同时记录拍照时机械臂末端法兰盘在基座下的位姿信息，每拍一次则驱动机械臂末端运动到空间中的另一个位姿，大约取20组左右数据即可。
3、标定Realsense D435点云坐标系与机械臂手眼关系时，需要注意D435点云数据的参考坐标系是否为标定时的相机坐标系。可以使用深度图(点云)对齐到RGB后的RGB图像进行标定。
4、RokaeXB4可能是能支持ROS的。两年前使用XB4时，与ROKAE沟通时确认了当时是有ROS-I&MoveIt的相关接口的，只不过当时接口还不够完善没有正式发布。建议再与Rokae沟通。
5、标定方法不唯一，可参考其他文献。本仓库中的手眼关系使用了比较取巧的方法，这里没有说。

**Comment by Twilight89** [comment]
@foxchys 
Thanks for your reply.
1、目前我大致理清了手眼标定(eye-to-hand)的标定流程：①获得相机多个坐标系到标定板坐标系的变换矩阵(matlab标定工具箱获得)；②同时获得多个机器人末端坐标系到机器人基坐标系的变换矩阵(由示教器中给出)；③使用Tsai的方法求解（[matlab程序](https://github.com/christianwengert/calib_toolbox_addon)）。如有错误或遗漏还望指点~
2、我有再三和珞石销售以及技术人员确定，他们的回复是目前的确不支持
